dcsc_tutoring/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from . import views

index = TemplateView.as_view(template_name='index.html')

urlpatterns = [
    url(r'^$', index),
    url(r'^home/$', index, name='index'),
    url(r'^tutors/', include('tutors.urls', namespace='tutors')),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^signup/', include('signup.urls', namespace='signup')),
    url(r'^admin/', include(admin.site.urls)),
]

signup/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^thanks/$', views.thanks, name='thanks'),
]

templates/layouts/default.html
{% load staticfiles %}
{% load tags %}
{% url 'index' as home %}
{% url 'tutors:index' as tutors %}
{% url 'schedule:index' as schedule %}
{% url 'signup:index' as signup %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'default.css' %}">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
  <title>CS Tutoring | {% block title %}{% endblock %}</title>
</head>
<body>
<header class="paper">
<a class="logo" href="https://daviscsclub.org/"><img height="27px" src="{% static 'logo.png' %}"></a>
<span class="site-name">Tutoring Committee</span>
</header>
<main>
<div class="content paper">
  {% block content %}{% endblock %}
</div>
<nav>
    <ul class="paper">
        <li class="{% active request 'home' %}">
        <a href="{{ home }}">Home</a>
        </li>
        <li class="{% active request 'tutors' %}">
        <a href="{{ tutors }}">Meet the Tutors</a>
        </li>
        <li class="{% active request 'schedule' %}">
        <a href="{{ schedule }}">Schedule</a>
        </li>
        <li class="{% active request 'signup' %}">
        <a href="{{ signup }}">Get Tutored</a>
        </li>
    </ul>
</nav>
</main>
<footer>
  <img class="bot" height="100px" src="{% static 'bot.svg' %}">
  <!-- This div prevents the flexbox from putting each <p> in a row -->
  <div>
      <p>&copy; 2015 Davis Computer Science Club</p>
      <p>This website is free software.  Check out the source code at
      wherever we put it.</p>
  </div>
</footer>
</body>
</html>